typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=204
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=204
typeset -g POWERLEVEL9K_ASDF_HASKELL_BACKGROUND=204
typeset -g POWERLEVEL9K_TIME_BACKGROUND=204
typeset -g POWERLEVEL9K_DIR_BACKGROUND=73

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
