version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=MyPass@word
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
