#!/bin/bash

# Activate specific venv and run your script
/Users/lnola/.python/venv/bin/python ~/bin/scripts/apply-config/apply_config.py

# Capture the exit code of the Python script
status=$?

if [ $status -ne 0 ]; then
  echo "Pre-commit check failed"
  exit $status
fi

exit 0

