#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.packageName Amethyst
# @raycast.title Relaunch Amethyst
# @raycast.mode silent

# Optional parameters:
# @raycast.icon ./assets/amethyst.png

# Documentation:
# @raycast.description Amethyst shortcut generated by generate_scripts.py
# @raycast.author Luka Nola

tell application "System Events"
    keystroke "z" using {option down, shift down, control down}
end tell
